### PR TITLE
Changing the evaluation of the database string

### PR DESCRIPTION
**Pull request by s9weber**
If a version for the database is specified in the string, it will be filtered out.

### CODE REVIEW

**Comment by jerome-barbato** [comment]
Hello, thank you for your PR, could you please paste here your complete database string ?

**Comment by s9weber** [comment]
The symfony standard DATABASE_URL look like that string:
DATABASE_URL="mysql://USER:PASSWORD@127.0.0.1:3306/DBNAME?serverVersion=5.7"

**Comment by jerome-barbato** [comment]
Thank you I have made and edit to your commit, do you confirm it's still working ?

**Comment by s9weber** [comment]
You are right. This also works and is the better solution.

**Review by s9weber — COMMENTED** [review]
That works.

**Pull request merged**
